### ISSUE TITLE
Canvas images broken for matrices and systems

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/checkit-tbil-la#13]
Systems of equations and matrices with multiple columns are not producing images in Canvas. 

<img width="721" alt="Screenshot 2021-02-02 201633" src="https://user-images.githubusercontent.com/30658947/106688445-c08d0f80-6593-11eb-831d-9f0949e682bf.png">

Note that single column vectors are okay. So I suspect ampersands are the problem. This worked fine when we used CodeCogs, so I wonder if this was introduced with the switch to Canvas generated image URLs.

Here is a generated exercise HTML that is not processing correctly.
```<div class="exercise-statement">
<p><strong>E1.</strong></p>
<p>Consider the augmented matrix</p>
<p style="text-align: center;"><img style="border: 1px #ddd solid; padding: 5px;" title="\left[\begin{array}{cccc|c} 1 &amp; 2 &amp; -4 &amp; 5 &amp; 1 \\ 0 &amp; 1 &amp; -3 &amp; 2 &amp; 1 \\ 3 &amp; 4 &amp; -6 &amp; 11 &amp; 1 \end{array}\right]" src="https://canvas.instructure.com/equation_images/%5Cleft%5B%5Cbegin%7Barray%7D%7Bcccc%7Cc%7D%201%20&amp;%202%20&amp;%20-4%20&amp;%205%20&amp;%201%20%5C%5C%200%20&amp;%201%20&amp;%20-3%20&amp;%202%20&amp;%201%20%5C%5C%203%20&amp;%204%20&amp;%20-6%20&amp;%2011%20&amp;%201%20%5Cend%7Barray%7D%5Cright%5D" alt="\left[\begin{array}{cccc|c} 1 &amp; 2 &amp; -4 &amp; 5 &amp; 1 \\ 0 &amp; 1 &amp; -3 &amp; 2 &amp; 1 \\ 3 &amp; 4 &amp; -6 &amp; 11 &amp; 1 \end{array}\right]" data-latex="\left[\begin{array}{cccc|c} 1 &amp; 2 &amp; -4 &amp; 5 &amp; 1 \\ 0 &amp; 1 &amp; -3 &amp; 2 &amp; 1 \\ 3 &amp; 4 &amp; -6 &amp; 11 &amp; 1 \end{array}\right]" /></p>
<ol type="a">
<li>Write a system of scalar equations corresponding to this augmented matrix.</li>
<li>Write a vector equation corresponding to this augmented matrix.</li>
</ol>
</div>```

**Comment by StevenClontz** [comment]
It seems we need to switch `&amp;` with `%26`. Let me see how obnoxious that will be...

**Comment by siwelwerd** [comment]
I just pulled in the first few question banks from last semester so I can build tomorrow's quiz and get us another week to sort this out.

**Comment by StevenClontz** [comment]
Mostly fixed here: https://github.com/StevenClontz/checkit/commit/54de511bd8b875a1f7a62d6e44f0d0015d58840d So you can rebuild from an updated CheckIt Dashboard and it should work.

This issue is now here: https://github.com/StevenClontz/checkit/issues/28
