### ISSUE TITLE
Setbuilder notation typesetting issue in Canvas

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/checkit-tbil-la#15]
<img width="569" alt="Screenshot 2021-02-05 083118" src="https://user-images.githubusercontent.com/30658947/107046706-8c307380-678c-11eb-9b14-b5a79efceeb1.png">

**Comment by StevenClontz** [comment]
Working on this (I've been wanting to refactor solution set generation anyway to be a simple function that takes an [augmented] matrix as its argument).

**Comment by StevenClontz** [comment]
Try building from the latest checkit and checkit-tbil-la commits. I believe this and #12 are fixed.

**Comment by StevenClontz** [comment]
I believe this is long-fixed.
