### ISSUE TITLE
Tweak E3 prompt

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/checkit-tbil-la#16]
Sometimes, a system given on E3 is simple enough to do by hand. I'd like the prompt to prevent this. One option is to simply make the systems all too complicated to do by hand. I think my preferred option would be to add a part (a) along the lines of "Write a simpler system that is equivalent to the original system" that would get them to write the system that goes with the RREF of the matrix (and then part (b) would be "Find the solution set"). This might also cut down on the error rate I see from students skipping the step of writing this simpler system.

**Comment by StevenClontz** [comment]
This is a good idea. It also synergizes with the model we've used for most outcomes recently: here's a thing, change it to this other simpler thing you've dealt with before, and use it to answer the question.

**Comment by StevenClontz** [comment]
That said, there's also more work that could be done with the random matrix generator to avoid zero rows and repeated columns.
