### ISSUE TITLE
E2 avoid long calculations while checking all three issues preventing RREF

### ISSUE THREAD

**Issue by StevenClontz** [TeamBasedInquiryLearning/checkit-tbil-la#23]
Would it make sense to have E2 give the student four matrices:

- one in RREF
- one with non-1 pivot
- one with non-0 above/below pivot
- one with non-descending pivots

Then have students find the RREF, explain what's wrong with the other three, then fix them?

I think this eliminates needing experience with full Gauss-Jordan elimination. To which I'd want to consider if this is bad: students can still learn it optionally if they want to do these RREFs by hand, but I'm also okay with them using tech all semester I think.

**Comment by StevenClontz** [comment]
(I guess we could still have a second part asking to find RREF of a matrix, but allow technology. Maybe that'd make a point.)

**Comment by siwelwerd** [comment]
Gaussian elimination is specifically listed in the course description here, and I assume many other places.  So my inclination is to keep it.

**Comment by siwelwerd** [comment]
I like it.  Maybe on 2, "Show step by step how to compute..."

**Comment by StevenClontz** [comment]
![image](https://user-images.githubusercontent.com/1559632/129244008-dfd065c5-c7a1-4553-a709-042ae47a199c.png)
