### ISSUE TITLE
A4 answers displaying incorrectly

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/checkit-tbil-la#28]
Via Matt Salomone:  A4 answers are not being handled correctly.

![Screenshot 2021-07-14 122623](https://user-images.githubusercontent.com/30658947/125665815-2fd97a0a-1547-4aff-a8b2-410321ac6095.jpg)

Might be the same kind of bug as in #27

**Comment by siwelwerd** [comment]
I think this is the issue

https://github.com/TeamBasedInquiryLearning/checkit-tbil-la/blob/7f6ca4f673d82b90132f635f21cdb29de5bc17c9/outcomes/A4.xml#L20

Should be `<p><m>T</m> is {{^surjective}}not {{/surjective}} surjective.</p>` if I'm not mistaken.

Not sure I like this use of the ^, that code is not semantic at all. Wouldn't something like   `<p><m>T</m> is {{#notsurjective}}not {{/notsurjective}} surjective.</p>` be more descriptive of what's happening?
``

**Comment by StevenClontz** [comment]
Your fix is correct and a hotfix will be committed to main shortly.

`{{#boolean}}shows if true{{/boolean}}` and `{{^boolean}}shows if false{{/boolean}}` are built into [Mustache](https://mustache.github.io/) - not what I would have chosen for syntax, but I decided that I didn't need to maintain my own templating system on top of all the other things I need to do for CheckIt, and Mustache has wide support for use in different contexts. We could manually set `{"notsurjective": not surjective}` in SageMath, but if we're adding extra lines I'd rather just make the template more explicit:

```
{{#surjective}}
  surjective.
{{/surjective}}
{{^surjective}}
  not surjective.
{{/surjective}}
```

**Comment by siwelwerd** [comment]
Sure, I like that better.  Maybe drop that in https://github.com/StevenClontz/checkit-platform/blob/main/templates.md as a best practice, and we can update any other places this shows up here.

**Comment by StevenClontz** [comment]
I've documented the practice - I'd say refactoring to fit that pattern is a low priority but I'm cool with sticking to the wordier but more explicit style in the future and as we adjust things anyway.
