### ISSUE TITLE
V3 logic might be broken

### ISSUE THREAD

**Issue by rhinopotamus** [TeamBasedInquiryLearning/checkit-tbil-la#40]
Every example I'm pulling up for V3 says that the vectors do **not** span RR^4, regardless of the shape of the rref. I suspect that whatever logic is generating the answer string is probably slightly broken.

**Comment by siwelwerd** [comment]
This also needs to be fixed in https://github.com/StevenClontz/checkit-tbil-la-2021-dev

**Comment by StevenClontz** [comment]
`builds/public/bank.json` is deprecated (and will be deleted shortly)

`docs/bank.json` is the live/public bank

`docs/builds/public/bank.json` is what makes the old version of CheckIt at https://checkit.clontz.org/0.0/ continue to work, and will be deleted in 2022.

**Comment by siwelwerd** [comment]
Maybe there was a caching issue? I didn't see it before, but now the public version now looks to be showing correctly.
