### ISSUE TITLE
LE3 Row of zeroes

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/checkit-tbil-la#44]
I would like to make all LE3 problems have four equations (still 3 variables), so that each one has a row of zeroes.  I suspect some students are noticing the pattern that a row of 0 0 0 | 1 means no solution, while the infinitely many solutions all have 0 0 0 | 0 .  I would rather reinforce the notion that a row 0 0 0 | 0 does not actually provide any information.

**Comment by StevenClontz** [comment]
This is done (as part of my work to port this bank to checkit 0.2)
