### ISSUE TITLE
Implement CheckIt's custom random matrix generator

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/checkit-tbil-la#6]
The systems in V9 could have a column of zeroes. This makes the solution ambiguous. For example, nothing in the context of the below problem implies the solution space should be a subspace of R^5 rather than R^4.

![V9](https://user-images.githubusercontent.com/30658947/95465925-59db4a80-0941-11eb-9fd3-1b6007202885.png)

**Comment by StevenClontz** [comment]
Now that https://github.com/StevenClontz/checkit/issues/17 is closed, this can be fixed. I implemented it for E1-V2 in 9818228. @siwelwerd can you take care of the rest based on those examples? If not I'll tackle this Mon/Tues next week.

**Comment by siwelwerd** [comment]
I get an error when I try to use Checkit now. I did a fresh copy of Checkit and the tbil-la problems, and am getting this error.

`from checkit import Bank
​
bank = Bank("checkit-tbil-la")
outcome = bank.outcome_from_slug("E2")
outcome.print_preview()
30.021 seconds
Generating 1 private exercises for E2... 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-cd6b5527b165> in <module>
      3 bank = Bank("checkit-tbil-la")
      4 outcome = bank.outcome_from_slug("E2")
----> 5 outcome.print_preview()

~/checkit/checkit.py in print_preview(self)
    273 
    274     def print_preview(self):
--> 275         ex = self.generate_exercises(amount=1,regenerate=True,save=False)[0]
    276         display(HTML("<h2>Preview:</h2> "+ex.html()))
    277         ex.print_preview()
~/checkit/checkit.py in generate_exercises(self, public, amount, regenerate, save)
    205         print(f"Generating {amount} {exs} for {self.slug}...",end=" ")
    206         # returns json list of exercise objects
--> 207         result = subprocess.run(command,capture_output=True)
    208         if result.stderr:
    209             print("ERROR, no exercises generated:")
/usr/lib/python3.6/subprocess.py in run(input, timeout, check, *popenargs, **kwargs)
    421         kwargs['stdin'] = PIPE
    422 
--> 423     with Popen(*popenargs, **kwargs) as process:
    424         try:
    425             stdout, stderr = process.communicate(input, timeout=timeout)
TypeError: __init__() got an unexpected keyword argument 'capture_output'`

**Comment by siwelwerd** [comment]
Ah, okay.  "Changed in version 3.7: Added the text parameter, as a more understandable alias of universal_newlines. Added the capture_output parameter."  The cocalc is running 3.6, and needs to be updated.  Checkit documentation should note that python >3.7 is required.
