### ISSUE TITLE
V6 prevent duplicate vectors

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/checkit-tbil-la#7]
V6 needs to check for duplicate vectors in the set.

**Comment by StevenClontz** [comment]
What I'm hearing is that CheckIt should provide a matrix generator that goes beyond the Sage one. We need to be able to plug in the dimensions and pivots, and we get back a random matrix that (1) uses integers between -9 and 9 for itself and its RREF, and (2) doesn't have repeated columns. Would that cover our bases?

**Comment by StevenClontz** [comment]
And (3) doesn't have a column of zeros for #6

**Comment by StevenClontz** [comment]
Merged with #6
